advpython/advdjango/advdjango/urls.py
from django.contrib import admin
from django.urls import path
from website import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^website/', include('website.urls', namespace='website')),
    # Tempalte base view URLs

    #Class base view URLs
    # url(r'^$', views.CBView.as_view())
    # url(r'^$', views.index)
]

advpython/advdjango/website/urls.py
from website import views
from django.conf.urls import url, include

app_name = 'website'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),


]

advpython/advdjango/website/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('website:detail', kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advpython/advdjango/website/views.py
from django.shortcuts import render
from django.views.generic import (View, ListView,
                                DetailView,TemplateView,
                                CreateView, UpdateView,
                                DeleteView)
from django.http import HttpResponse
from . import models
from website import views
from django.urls import reverse_lazy

# Class base views
class IndexView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Mian Amir Savvy'
        return context


class SchoolListView(ListView):
    # context_object_name = 'schools'
    model = models.School
    # template_name = 'website/school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'website/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("website:list")



# class CBView(View):
#     def get(self, request):
#         return HttpResponse("Amir Savvy in CBV")



# Create your views here.
# def index(request):
#     return render(request, 'index.html')

advpython/advdjango/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base Template</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

  </head>
  <body>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

advpython/advdjango/templates/index.html
{% extends "base.html" %}

{% block body_block %}
<h1>Amir Savvy, Template Base Index Page</h1>
<h3>My Full Name: {{ name }}</h3>

<h3><a href="{% url 'website:list' %}">Schools</a></h3>
<h3><a href="{% url 'admin:index' %}">Admin</a></h3>
{% endblock %}

advpython/advdjango/website/templates/website/school_confirm_delete.html
{% extends "website/website_base.html" %}

{% block body_block %}

<h1>Delete {{school.name}} ?</h1>
<form method="post">
{% csrf_token %}
<input type="submit" name="" value="Delete" class="btn btn-danger">
<a href="{% url 'website:list' %}">Cancel</a>

</form>

{% endblock %}

advpython/advdjango/website/templates/website/school_detail.html
{% extends 'website/website_base.html' %}


{% block body_block %}
<div class="container">
  <div class="row">
<h1>Welcome to School Details Page</h1>
<h2>School Name: {{school_detail.name}}</h2>
<h2>School principal: {{school_detail.principal}}</h2>
<h2>School Location: {{school_detail.location}}</h2>

<h1>This School has following students</h1>

{% for student in school_detail.student_set.all %}
  <h3>{{student.name}} who is {{student.age}} years old.</h3>
{% endfor %}
</div>

<div class="row">
<a class="btn btn-warning" href="{% url 'website:update' pk=school_detail.pk %}">
  Update School</a>
</div>
<a class="btn btn-danger" href="{% url 'website:delete' pk=school_detail.pk %}">
  Delete School</a>
</div>

</div>
{% endblock %}

advpython/advdjango/website/templates/website/school_form.html
{% extends "website/website_base.html" %}
% load crispy_forms_tags %}

{% block body_block %}

<h1>
{% if not form.instance.pk %}
Create School
{% else %}
Update School
{% endif %}

</h1>

<form method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-primary" value="Submit">

</form>





{% endblock %}

advpython/advdjango/website/templates/website/school_list.html
{% extends "website/website_base.html" %}

{% block body_block %}

<h1>All Schools</h1>

<ol>
{% for school in school_list %}
  <h2><li><a href="{{school.id}}">{{ school.name }}</a></li></h2>
{% endfor %}

</ol>

{% endblock %}

advpython/advdjango/website/templates/website/website_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Website</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
    <h1>Website Home page</h1>
    <h3><a href="{% url 'website:list' %}"> Schools </a></h3>
    <h3><a href="{% url 'admin:index' %}">Admin</a></h3>

    {% block body_block %}

    {% endblock %}

</div>
  </body>
</html>